// Auth
export const LOGIN_SUCCES = 'LOGIN_SUCCES';
export const USER_LOADED = 'USER_LOADED';
export const LOGOUT = 'LOGOUT';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const REGISTER_SUCCES = 'REGISTER_SUCCES';

// Alert
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// Profile
export const LOAD_PROFILE = 'LOAD_PROFILE';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const SET_PROFILE = 'SET_PROFILE';
export const ADD_ERROR = 'ADD_ERROR';
export const REMOVE_ERROR = 'REMOVE_ERROR';
export const SET_BMR = 'SET_BMR';
export const SET_CALORIES = 'SET_CALORIES';
export const SET_LOADING_PROFILE = 'SET_LOADING_PROFILE';

// Food
export const ADD_ERROR_FOOD = 'ADD_ERROR_FOOD';
export const REMOVE_ERROR_FOOD = 'REMOVE_ERROR_FOOD';
export const CLEAR_ALL_ERROR_FOOD = 'CLEAR_ALL_ERROR_FOOD';
export const CREATE_FOOD = 'CREATE_FOOD';
export const UPDATE_FOOD = 'UPDATE_FOOD';
export const GET_FOOD = 'GET_FOOD';
export const CLEAR_FOOD = 'CLEAR_FOOD';
export const EDIT_FOOD_READY = 'EDIT_FOOD_READY';
export const GET_SEARCH_FOOD = 'GET_SEARCH_FOOD';

// Food Entries
export const GET_FOOD_ENTRIES = 'GET_FOOD_ENTRIES';
export const SET_FOOD_ENTRIES = 'SET_FOOD_ENTRIES';
export const SET_DATE = 'SET_DATE';
export const SET_MOMENT = 'SET_MOMENT';
export const SET_SELECTED_FOOD = 'SET_SELECTED_FOOD';
export const REMOVE_SELECTED_FOOD = 'REMOVE_SELECTED_FOOD';
export const CLEAR_SELECTED_FOOD = 'CLEAR_SELECTED_FOOD';
export const SET_AMOUNT = 'SET_AMOUNT';
export const CLEAR_FOOD_ENTRIES = 'CLEAR_FOOD_ENTRIES';
export const SET_SELECTED_FOOD_LIST = 'SET_SELECTED_FOOD_LIST';
export const SET_LOADING_FOOD_ENTRIES = 'SET_LOADING_FOOD_ENTRIES';
export const CALC_TOTALS_DONE = 'CALC_TOTALS_DONE';
export const SET_HOME_TOTALS = 'SET_HOME_TOTALS';
